added the editor config file
BIT-Studio-3/Space-Rescue pull request #159
Opened 2023-08-23 02:41 UTC by ChaseBENNC9

## Describe your changes

This will add a new workflow that will automatically check and format the whitespace of changed scripts and commit any changes it makes.

Originally this was meant to include code consistency including variable naming and methods but this is not possible either due to conflicts with unity or GitHub actions.

There is also a validation that can be done locally using something called a pre-commit hook. However I am unsure if this will work the way I am intending it to and how it would be setup easily. because every machine would need to manually add this script.

I don't want to add this to our main repo until it is completely working because at this point it will be active as soon as i commit it.  So I could just comment out the code until it is ready but for now everything is accessible on my fork link and I will add some instructions on how to test it to the CI wiki page link.

## Issue number and link

#139 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

2023-08-27 05:45 UTC, PBWiseman requested changes
Attempted to test this out on the other repo and it failed. Got this response 
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/104882337/e47c0ec5-9d24-435a-abb2-c3139f12f920)
Links: https://github.com/ChaseBENNC9/Space-Rescue/pull/41
https://github.com/ChaseBENNC9/Space-Rescue/actions/runs/5989176525/job/16245087238?pr=41

2023-08-27 08:57 UTC, ChaseBENNC9 commented
> Attempted to test this out on the other repo and it failed. Got this response ![image](https://user-images.githubusercontent.com/104882337/263510758-e47c0ec5-9d24-435a-abb2-c3139f12f920.png) Links: [ChaseBENNC9#41](https://github.com/ChaseBENNC9/Space-Rescue/pull/41) https://github.com/ChaseBENNC9/Space-Rescue/actions/runs/5989176525/job/16245087238?pr=41

I'm pretty sure I figured out the issue. When the branch is first created it activates the workflow. But it can't access the hash of the previous commit. from what i can see this is only going to happen on the first time the branch is created. I am going to see if i can either get it to skip when this is the case or better - get the difference between main for the initial change. Ideally in the main repo there wont be a change made while making the branch and it should hopefully still work as intended

2023-08-27 09:33 UTC, PBWiseman commented
> > Attempted to test this out on the other repo and it failed. Got this response ![image](https://user-images.githubusercontent.com/104882337/263510758-e47c0ec5-9d24-435a-abb2-c3139f12f920.png) Links: [ChaseBENNC9#41](https://github.com/ChaseBENNC9/Space-Rescue/pull/41) https://github.com/ChaseBENNC9/Space-Rescue/actions/runs/5989176525/job/16245087238?pr=41
> 
> I'm pretty sure I figured out the issue. When the branch is first created it activates the workflow. But it can't access the hash of the previous commit. from what i can see this is only going to happen on the first time the branch is created. I am going to see if i can either get it to skip when this is the case or better - get the difference between main for the initial change. Ideally in the main repo there wont be a change made while making the branch and it should hopefully still work as intended

Tested it again with a new commit and works well.

2023-08-27 09:33 UTC, PBWiseman approved these changes

2023-08-29 01:29 UTC, erokasyuart approved these changes

2023-08-29 01:30 UTC, 3MKJOE58 approved these changes

2023-08-29 01:38 UTC, merged