Merge pull request #197 from BIT-Studio-3/staging
BIT-Studio-3/Space-Rescue pull request #209
Opened 2023-10-11 21:46 UTC by 3MKJOE58

V1.10.0

## Describe your changes

Changing spaceship turning speed 

## Issue number and link

#208
#(Issue number this is fixing)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have written any applicable tests
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

2023-10-16 23:08 UTC, PBWiseman requested changes
Definitely an improvement! I noticed in the code the value of mouseSensitivity is .3f and in the editor it is .5f. Which one was intended? .5f still feels a little fast personally but I'd like to hear others opinion on it.

2023-10-18 06:47 UTC, erokasyuart requested changes
I'm somebody who plays with mouse sensitivity turned all the way up. Personally, this feels very very slow and hard to turn, but others might think it's too fast. I think the resolution to this is to implement something that is a spectrum, so it fits all users' needs. Some people have said the flying is very motion sickness-inducing, but for me, I couldn't care less! I think it would be most useful to add a slider into the settings menu that changes the value! I think sliders are fairly simple to understand, I don't think it will take you long at all!

2023-10-18 07:37 UTC, PBWiseman commented
> I'm somebody who plays with mouse sensitivity turned all the way up. Personally, this feels very very slow and hard to turn, but others might think it's too fast. I think the resolution to this is to implement something that is a spectrum, so it fits all users' needs. Some people have said the flying is very motion sickness-inducing, but for me, I couldn't care less! I think it would be most useful to add a slider into the settings menu that changes the value! I think sliders are fairly simple to understand, I don't think it will take you long at all!

Oh a slider is a really good idea! Seconded!

2023-10-18 21:33 UTC, ChaseBENNC9 requested changes
I think it is definitely an improvement. But i agree with other reviewers in that it is slightly slow. And I agree that a slider would provide a wide range of options for different players

2023-10-24 01:00 UTC, erokasyuart requested changes
Good improvement to the movement. Highly adjustable for players preferences.

Just some slight tweaks needed:
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/740dbf92-69db-41b4-8f1e-1fada23a7958)
Probably best to remove "volume" from Mouse Sensitivity Text

2023-10-24 01:00 UTC, erokasyuart commented on Assets/Scripts/Ship Movement/ShipMovement.cs
> -        Cursor.lockState = CursorLockMode.Locked; //keep mouse in the game
Add this back in! At the very start of the game, when main scene is first loaded, the mouse is not locked.

2023-10-24 01:04 UTC, PBWiseman requested changes
Great work. The slider works properly and the sensitivity changes. Minor tweaks needed:
Can there please be a minimum sliver value set? This can be done on the slider game object and make sure that the player doesn't reduce the value to 0 and not be able to fly.
The text for mouse sensitivity slider should probably remove the Volume part as it isn't really a volume.
The mouse sensitivity slider is a little bit out of alignment with the other settings. If you set the Y position of all the objects inside of the Mouse Sensitivity parent (text, slider, and number) and change the y position of the parent to -140 to continue the 70 gap then that would look more even.

2023-10-24 01:08 UTC, ChaseBENNC9 requested changes
Slider works great definitely allows players to customize their experience. Once thing I noticed was you can set the slider to 0 which isn't something you'd expect in a sensitivity slider. An easy way to change this is in the sensitivity slider in the settings scene and changes min from 0 to to 0.1,

2023-10-24 01:21 UTC, ChaseBENNC9 approved these changes

2023-10-24 01:22 UTC, PBWiseman approved these changes

2023-10-24 01:28 UTC, erokasyuart approved these changes
Swagalicious!

2023-10-24 01:28 UTC, merged